FROM cmdln/crossbuild

ARG RUST_VER
ARG OPENSSL_VER

#RUN apt update && \
#        apt upgrade -y

ENV OPENSSL_DIR /usr/local/
ENV OPENSSL_STATIC=1

ADD build_openssl.sh .

RUN ./build_openssl.sh

ENV PATH "/root/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

RUN curl https://sh.rustup.rs -sSf -o rustup.sh && \
        sh ./rustup.sh -y && \
        rustup default $RUST_VER && \
        rm rustup.sh

CMD ["cargo", "build", "--release"]
