#!/bin/bash

# based on https://gist.github.com/luser/a33e5070d1c55a7d2c46fe763a9d1543

set -e

mkdir -p .cargo
if [ -f .cargo/config ]
then
    mv .cargo/config .cargo/config.bak
fi
# Point cargo at the cross-toolchain.
cat > .cargo/config <<EOF
[target.x86_64-apple-darwin]
linker = "/usr/local/bin/mac-cc"
ar = "/usr/osxcross/bin/x86_64-apple-darwin15-ar"
EOF

# Build it.
cmd="${1}"
shift 1
cargo "${cmd}" --target=x86_64-apple-darwin "$@"
if [ -f .cargo/config.bak ]
then
    mv .cargo/config.bak .cargo/config
else
    rm .cargo/config
fi
